### ISSUE TITLE
Markdown Schema

### ISSUE THREAD

**Issue by illycz** [storyblok/silex-boilerplate#8]
If I try use markdown fieldtype, outputed HTML is escaped.
Paragraph like this: `&lt;p&gt;Test&lt;/p&gt;`

My twig code:
```
{{ blok._editable }}

<div class="markdown">
	{{ blok.text | markdown }}
</div>
```

Thanks

**Comment by onefriendaday** [comment]
Hi!

I updated the filter adding `array('is_safe' => array('html'))` to output html.
https://github.com/storyblok/silex-boilerplate/blob/master/webapp/src/App/Helpers/Twig.php

Cheers,
Alex
